# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: WebProtocol.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='WebProtocol.proto',
  package='psmweb',
  serialized_pb=_b('\n\x11WebProtocol.proto\x12\x06psmweb\"g\n\x17wsProcessCommandRequest\x12\r\n\x05token\x18\x01 \x02(\x05\x12(\n\x04type\x18\x02 \x02(\x0e\x32\x1a.psmweb.ProcessCommandType\x12\x13\n\x0bprocessName\x18\x03 \x02(\t\"\xc4\x01\n\x18swProcessCommandResponse\x12\r\n\x05token\x18\x01 \x02(\x05\x12(\n\x04type\x18\x02 \x02(\x0e\x32\x1a.psmweb.ProcessCommandType\x12\x37\n\x06result\x18\x03 \x02(\x0e\x32\'.psmweb.swProcessCommandResponse.Result\x12\x12\n\nfailReason\x18\x04 \x01(\t\"\"\n\x06Result\x12\x0b\n\x07SUCCESS\x10\x00\x12\x0b\n\x07\x46\x41ILURE\x10\x01\"\x0f\n\rwsHealthCheck\"\r\n\x0bswHealthAck*`\n\x07psmType\x12\x19\n\x15ProcessCommandRequest\x10\x00\x12\x1a\n\x16ProcessCommandResponse\x10\x01\x12\x0f\n\x0bHealthCheck\x10\x08\x12\r\n\tHealthAck\x10\t*`\n\x12ProcessCommandType\x12\t\n\x05START\x10\x00\x12\x0b\n\x07RESTART\x10\x01\x12\x08\n\x04STOP\x10\x02\x12\x0b\n\x07\x41\x44\x44LIST\x10\x03\x12\x0e\n\nDELETELIST\x10\x04\x12\x0b\n\x07\x41LLSTOP\x10\x05')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_PSMTYPE = _descriptor.EnumDescriptor(
  name='psmType',
  full_name='psmweb.psmType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ProcessCommandRequest', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ProcessCommandResponse', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='HealthCheck', index=2, number=8,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='HealthAck', index=3, number=9,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=365,
  serialized_end=461,
)
_sym_db.RegisterEnumDescriptor(_PSMTYPE)

psmType = enum_type_wrapper.EnumTypeWrapper(_PSMTYPE)
_PROCESSCOMMANDTYPE = _descriptor.EnumDescriptor(
  name='ProcessCommandType',
  full_name='psmweb.ProcessCommandType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='START', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RESTART', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='STOP', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ADDLIST', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DELETELIST', index=4, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ALLSTOP', index=5, number=5,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=463,
  serialized_end=559,
)
_sym_db.RegisterEnumDescriptor(_PROCESSCOMMANDTYPE)

ProcessCommandType = enum_type_wrapper.EnumTypeWrapper(_PROCESSCOMMANDTYPE)
ProcessCommandRequest = 0
ProcessCommandResponse = 1
HealthCheck = 8
HealthAck = 9
START = 0
RESTART = 1
STOP = 2
ADDLIST = 3
DELETELIST = 4
ALLSTOP = 5


_SWPROCESSCOMMANDRESPONSE_RESULT = _descriptor.EnumDescriptor(
  name='Result',
  full_name='psmweb.swProcessCommandResponse.Result',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SUCCESS', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FAILURE', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=297,
  serialized_end=331,
)
_sym_db.RegisterEnumDescriptor(_SWPROCESSCOMMANDRESPONSE_RESULT)


_WSPROCESSCOMMANDREQUEST = _descriptor.Descriptor(
  name='wsProcessCommandRequest',
  full_name='psmweb.wsProcessCommandRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='token', full_name='psmweb.wsProcessCommandRequest.token', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='type', full_name='psmweb.wsProcessCommandRequest.type', index=1,
      number=2, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='processName', full_name='psmweb.wsProcessCommandRequest.processName', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=29,
  serialized_end=132,
)


_SWPROCESSCOMMANDRESPONSE = _descriptor.Descriptor(
  name='swProcessCommandResponse',
  full_name='psmweb.swProcessCommandResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='token', full_name='psmweb.swProcessCommandResponse.token', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='type', full_name='psmweb.swProcessCommandResponse.type', index=1,
      number=2, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='result', full_name='psmweb.swProcessCommandResponse.result', index=2,
      number=3, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='failReason', full_name='psmweb.swProcessCommandResponse.failReason', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _SWPROCESSCOMMANDRESPONSE_RESULT,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=135,
  serialized_end=331,
)


_WSHEALTHCHECK = _descriptor.Descriptor(
  name='wsHealthCheck',
  full_name='psmweb.wsHealthCheck',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=333,
  serialized_end=348,
)


_SWHEALTHACK = _descriptor.Descriptor(
  name='swHealthAck',
  full_name='psmweb.swHealthAck',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=350,
  serialized_end=363,
)

_WSPROCESSCOMMANDREQUEST.fields_by_name['type'].enum_type = _PROCESSCOMMANDTYPE
_SWPROCESSCOMMANDRESPONSE.fields_by_name['type'].enum_type = _PROCESSCOMMANDTYPE
_SWPROCESSCOMMANDRESPONSE.fields_by_name['result'].enum_type = _SWPROCESSCOMMANDRESPONSE_RESULT
_SWPROCESSCOMMANDRESPONSE_RESULT.containing_type = _SWPROCESSCOMMANDRESPONSE
DESCRIPTOR.message_types_by_name['wsProcessCommandRequest'] = _WSPROCESSCOMMANDREQUEST
DESCRIPTOR.message_types_by_name['swProcessCommandResponse'] = _SWPROCESSCOMMANDRESPONSE
DESCRIPTOR.message_types_by_name['wsHealthCheck'] = _WSHEALTHCHECK
DESCRIPTOR.message_types_by_name['swHealthAck'] = _SWHEALTHACK
DESCRIPTOR.enum_types_by_name['psmType'] = _PSMTYPE
DESCRIPTOR.enum_types_by_name['ProcessCommandType'] = _PROCESSCOMMANDTYPE

wsProcessCommandRequest = _reflection.GeneratedProtocolMessageType('wsProcessCommandRequest', (_message.Message,), dict(
  DESCRIPTOR = _WSPROCESSCOMMANDREQUEST,
  __module__ = 'WebProtocol_pb2'
  # @@protoc_insertion_point(class_scope:psmweb.wsProcessCommandRequest)
  ))
_sym_db.RegisterMessage(wsProcessCommandRequest)

swProcessCommandResponse = _reflection.GeneratedProtocolMessageType('swProcessCommandResponse', (_message.Message,), dict(
  DESCRIPTOR = _SWPROCESSCOMMANDRESPONSE,
  __module__ = 'WebProtocol_pb2'
  # @@protoc_insertion_point(class_scope:psmweb.swProcessCommandResponse)
  ))
_sym_db.RegisterMessage(swProcessCommandResponse)

wsHealthCheck = _reflection.GeneratedProtocolMessageType('wsHealthCheck', (_message.Message,), dict(
  DESCRIPTOR = _WSHEALTHCHECK,
  __module__ = 'WebProtocol_pb2'
  # @@protoc_insertion_point(class_scope:psmweb.wsHealthCheck)
  ))
_sym_db.RegisterMessage(wsHealthCheck)

swHealthAck = _reflection.GeneratedProtocolMessageType('swHealthAck', (_message.Message,), dict(
  DESCRIPTOR = _SWHEALTHACK,
  __module__ = 'WebProtocol_pb2'
  # @@protoc_insertion_point(class_scope:psmweb.swHealthAck)
  ))
_sym_db.RegisterMessage(swHealthAck)


# @@protoc_insertion_point(module_scope)
